#!/usr/bin/env node
// @generated by mcp-google-workspace@1.0.0 on 2026-02-23T05:35:00.051Z. DO NOT EDIT.
import { Command } from 'commander';
import { createRuntime, createServerProxy } from 'mcporter';
import { createCallResult } from 'mcporter';

const embeddedServer = {
  "name": "index",
  "command": {
    "kind": "stdio",
    "command": "node",
    "args": [
      "/home/tyler/mcp-google-workspace/mcp/dist/index.js"
    ]
  },
  "source": {
    "kind": "local",
    "path": "<adhoc>"
  },
  "description": "mcp-google-workspace"
} as const;
const embeddedSchemas = {
  "gmail_search": {
    "type": "object",
    "properties": {
      "query": {
        "type": "string",
        "description": "Gmail search query (same syntax as the Gmail search bar)"
      },
      "maxResults": {
        "type": "integer",
        "minimum": 1,
        "maximum": 50,
        "default": 10,
        "description": "Maximum number of threads to return (1-50, default 10)"
      }
    },
    "required": [
      "query"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "gmail_get_message": {
    "type": "object",
    "properties": {
      "messageId": {
        "type": "string",
        "description": "The Gmail message ID to retrieve"
      }
    },
    "required": [
      "messageId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "gmail_send_draft": {
    "type": "object",
    "properties": {
      "to": {
        "type": "string",
        "description": "Recipient email address"
      },
      "subject": {
        "type": "string",
        "description": "Email subject"
      },
      "body": {
        "type": "string",
        "description": "Plain text email body"
      },
      "cc": {
        "type": "string",
        "description": "CC recipients (comma-separated)"
      },
      "bcc": {
        "type": "string",
        "description": "BCC recipients (comma-separated)"
      }
    },
    "required": [
      "to",
      "subject",
      "body"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "gmail_get_messages": {
    "type": "object",
    "properties": {
      "query": {
        "type": "string",
        "description": "Gmail search query (e.g. \"is:unread\", \"from:boss@company.com\")"
      },
      "maxResults": {
        "type": "integer",
        "minimum": 1,
        "maximum": 20,
        "default": 5,
        "description": "Max threads to expand, each with all messages (1-20, default 5)"
      }
    },
    "required": [
      "query"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "gmail_modify_message": {
    "type": "object",
    "properties": {
      "messageId": {
        "type": "string",
        "description": "The Gmail message ID to modify"
      },
      "markRead": {
        "type": "boolean",
        "description": "true = mark as read, false = mark as unread"
      },
      "star": {
        "type": "boolean",
        "description": "true = star the message, false = unstar"
      },
      "trash": {
        "type": "boolean",
        "description": "true = move the message to Trash"
      },
      "archive": {
        "type": "boolean",
        "description": "true = archive the thread (remove from Inbox)"
      }
    },
    "required": [
      "messageId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "gmail_label_message": {
    "type": "object",
    "properties": {
      "threadId": {
        "type": "string",
        "description": "The Gmail thread ID to label"
      },
      "labelName": {
        "type": "string",
        "description": "Label name to apply or remove. Created automatically on \"add\" if it does not exist."
      },
      "action": {
        "type": "string",
        "enum": [
          "add",
          "remove"
        ],
        "description": "\"add\" to apply the label, \"remove\" to remove it"
      }
    },
    "required": [
      "threadId",
      "labelName",
      "action"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "calendar_list_events": {
    "type": "object",
    "properties": {
      "calendarId": {
        "type": "string",
        "default": "primary",
        "description": "Calendar ID (default: \"primary\")"
      },
      "timeMin": {
        "type": "string",
        "description": "Start of time range in ISO 8601 format (defaults to now)"
      },
      "timeMax": {
        "type": "string",
        "description": "End of time range in ISO 8601 format"
      },
      "maxResults": {
        "type": "integer",
        "minimum": 1,
        "maximum": 50,
        "default": 10,
        "description": "Max events to return (1-50, default 10)"
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "calendar_create_event": {
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "description": "Event title / summary"
      },
      "start": {
        "type": "string",
        "description": "Event start time in ISO 8601 format"
      },
      "end": {
        "type": "string",
        "description": "Event end time in ISO 8601 format"
      },
      "calendarId": {
        "type": "string",
        "default": "primary",
        "description": "Calendar ID (default: \"primary\")"
      },
      "description": {
        "type": "string",
        "description": "Event description"
      },
      "location": {
        "type": "string",
        "description": "Event location"
      },
      "attendees": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "List of attendee email addresses"
      },
      "sendInvites": {
        "type": "boolean",
        "default": true,
        "description": "Whether to send invite emails (default: true)"
      }
    },
    "required": [
      "title",
      "start",
      "end"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "calendar_smart_search": {
    "type": "object",
    "properties": {
      "startDate": {
        "type": "string",
        "description": "Start of the date range in ISO 8601 format (e.g. \"2026-02-20\")"
      },
      "endDate": {
        "type": "string",
        "description": "End of the date range in ISO 8601 format (e.g. \"2026-02-27\")"
      }
    },
    "required": [
      "startDate",
      "endDate"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "calendar_check_conflicts": {
    "type": "object",
    "properties": {
      "proposedStart": {
        "type": "string",
        "description": "Proposed event start time in ISO 8601 format"
      },
      "proposedEnd": {
        "type": "string",
        "description": "Proposed event end time in ISO 8601 format"
      }
    },
    "required": [
      "proposedStart",
      "proposedEnd"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "calendar_quick_add": {
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "description": "Natural-language event description (e.g. \"Lunch with Sarah next Tuesday at 1pm\")"
      },
      "calendarId": {
        "type": "string",
        "default": "primary",
        "description": "Calendar ID (default: \"primary\")"
      }
    },
    "required": [
      "text"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "calendar_daily_briefing": {
    "type": "object",
    "properties": {
      "date": {
        "type": "string",
        "description": "Date in ISO 8601 format (e.g. \"2026-02-20\"). Defaults to today."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "calendar_block_focus_time": {
    "type": "object",
    "properties": {
      "durationMinutes": {
        "type": "integer",
        "minimum": 15,
        "description": "Focus block length in minutes (e.g. 90 for 1.5 hours)"
      },
      "withinNextNDays": {
        "type": "integer",
        "minimum": 1,
        "maximum": 30,
        "default": 7,
        "description": "Days ahead to scan for a free slot (default: 7, max: 30). Weekdays 9 AM–6 PM only."
      },
      "calendarId": {
        "type": "string",
        "default": "primary",
        "description": "Calendar to book the focus block on (default: \"primary\")"
      }
    },
    "required": [
      "durationMinutes"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_search": {
    "type": "object",
    "properties": {
      "query": {
        "type": "string",
        "description": "Drive search query (e.g. \"name contains 'report'\" or \"mimeType='application/vnd.google-apps.document'\")"
      },
      "maxResults": {
        "type": "integer",
        "minimum": 1,
        "maximum": 50,
        "default": 10,
        "description": "Max files to return (1-50, default 10)"
      }
    },
    "required": [
      "query"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_get_file": {
    "type": "object",
    "properties": {
      "fileId": {
        "type": "string",
        "description": "The Drive file ID"
      }
    },
    "required": [
      "fileId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_export_file": {
    "type": "object",
    "properties": {
      "fileId": {
        "type": "string",
        "description": "The Drive file ID to export"
      },
      "mimeType": {
        "type": "string",
        "default": "text/plain",
        "description": "Target MIME type (default: \"text/plain\"). Use \"application/pdf\" for PDFs. Binary files are returned as base64."
      }
    },
    "required": [
      "fileId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_list_folder": {
    "type": "object",
    "properties": {
      "folderId": {
        "type": "string",
        "description": "The Drive folder ID to list. Use \"root\" for My Drive root."
      },
      "maxResults": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100,
        "default": 50,
        "description": "Max items to return (default: 50)"
      }
    },
    "required": [
      "folderId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_read_doc_markdown": {
    "type": "object",
    "properties": {
      "fileId": {
        "type": "string",
        "description": "The Google Doc file ID to convert to Markdown"
      }
    },
    "required": [
      "fileId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_read_sheet_csv": {
    "type": "object",
    "properties": {
      "fileId": {
        "type": "string",
        "description": "The Google Sheets file ID to export as CSV"
      },
      "sheetName": {
        "type": "string",
        "description": "Sheet/tab name (defaults to the active sheet)"
      },
      "range": {
        "type": "string",
        "description": "A1 notation range (e.g. \"A1:E20\"). Defaults to all data."
      }
    },
    "required": [
      "fileId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_slides_as_text": {
    "type": "object",
    "properties": {
      "fileId": {
        "type": "string",
        "description": "The Google Slides file ID to extract text from"
      }
    },
    "required": [
      "fileId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_organize_files": {
    "type": "object",
    "properties": {
      "fileIds": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 1,
        "description": "Array of Drive file IDs to move"
      },
      "targetFolderId": {
        "type": "string",
        "description": "The destination folder ID"
      }
    },
    "required": [
      "fileIds",
      "targetFolderId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_create_shortcut": {
    "type": "object",
    "properties": {
      "fileId": {
        "type": "string",
        "description": "The Drive file ID to create a shortcut for"
      },
      "folderId": {
        "type": "string",
        "description": "Folder ID where the shortcut is placed. Use \"root\" for My Drive root."
      }
    },
    "required": [
      "fileId",
      "folderId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_manage_permissions": {
    "type": "object",
    "properties": {
      "fileId": {
        "type": "string",
        "description": "The Drive file ID to manage permissions for"
      },
      "email": {
        "type": "string",
        "format": "email",
        "description": "Email address of the user to grant or revoke access"
      },
      "role": {
        "type": "string",
        "enum": [
          "viewer",
          "commenter",
          "editor"
        ],
        "default": "viewer",
        "description": "Access level (default: \"viewer\"). Only used when action is \"add\"."
      },
      "action": {
        "type": "string",
        "enum": [
          "add",
          "remove"
        ],
        "description": "\"add\" to grant access, \"remove\" to revoke it"
      }
    },
    "required": [
      "fileId",
      "email",
      "action"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_summarize_folder": {
    "type": "object",
    "properties": {
      "folderId": {
        "type": "string",
        "description": "The Drive folder ID to summarize. Use \"root\" for My Drive root."
      },
      "maxFiles": {
        "type": "integer",
        "minimum": 1,
        "maximum": 20,
        "default": 10,
        "description": "Max files to include (default: 10, max: 20)"
      }
    },
    "required": [
      "folderId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drive_find_and_replace": {
    "type": "object",
    "properties": {
      "fileIds": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 1,
        "description": "Array of Google Doc file IDs to run find-and-replace on"
      },
      "find": {
        "type": "string",
        "description": "Text (or regex) to search for"
      },
      "replace": {
        "type": "string",
        "description": "Replacement text"
      }
    },
    "required": [
      "fileIds",
      "find",
      "replace"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "docs_create": {
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "description": "Title for the new Google Doc"
      },
      "content": {
        "type": "string",
        "description": "Initial body text for the document"
      }
    },
    "required": [
      "title"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "docs_get": {
    "type": "object",
    "properties": {
      "docId": {
        "type": "string",
        "description": "The Google Doc ID"
      }
    },
    "required": [
      "docId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "docs_append": {
    "type": "object",
    "properties": {
      "docId": {
        "type": "string",
        "description": "The Google Doc ID to append to"
      },
      "content": {
        "type": "string",
        "description": "The text content to append"
      },
      "addNewline": {
        "type": "boolean",
        "default": true,
        "description": "Add a blank line before the appended content (default: true)"
      }
    },
    "required": [
      "docId",
      "content"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  }
} as const;
const embeddedName = "index";
const embeddedDescription = "mcp-google-workspace";
const generatorInfo = "Generated by mcp-google-workspace@1.0.0 — https://github.com/steipete/mcporter";
const generatorTools = [
  {
    "name": "gmail-search",
    "description": "Search Gmail threads using the same query syntax as the Gmail search bar. Returns thread metadata including subject, sender, date, and read status.",
    "usage": "gmail-search --query <query> [--max-results <max-results:number>] [--raw <json>]",
    "flags": "--query <query> [--max-results <max-results:number>] [--raw <json>]"
  },
  {
    "name": "gmail-get-message",
    "description": "Retrieve the full content of a single Gmail message by its ID, including headers, plain-text body, and attachment metadata.",
    "usage": "gmail-get-message --message-id <message-id> [--raw <json>]",
    "flags": "--message-id <message-id> [--raw <json>]"
  },
  {
    "name": "gmail-send-draft",
    "description": "Create a Gmail draft and immediately send it.",
    "usage": "gmail-send-draft --to <to> --subject <subject> --body <body> [--cc <cc>] [--bcc <bcc>] [--raw <json>]",
    "flags": "--to <to> --subject <subject> --body <body> [--cc <cc>] [--bcc <bcc>] [--raw <json>]"
  },
  {
    "name": "gmail-get-messages",
    "description": "Bulk-fetch full message content (subject, headers, body, attachments) for all emails matching a Gmail search query. Ideal for \"get all unread emails\" type requests.",
    "usage": "gmail-get-messages --query <query> [--max-results <max-results:number>] [--raw <json>]",
    "flags": "--query <query> [--max-results <max-results:number>] [--raw <json>]"
  },
  {
    "name": "gmail-modify-message",
    "description": "Modify the state of a Gmail message: mark it read/unread, star/unstar it, move it to trash, or archive its thread.",
    "usage": "gmail-modify-message --message-id <message-id> [--mark-read <mark-read:true|false>] [--star <star:true|false>] [--trash <trash:true|false>] [--archive <archive:true|false>] [--raw <json>]",
    "flags": "--message-id <message-id> [--mark-read <mark-read:true|false>] [--star <star:true|false>] [--trash <trash:true|false>] [--archive <archive:true|false>] [--raw <json>]"
  },
  {
    "name": "gmail-label-message",
    "description": "Apply or remove a named Gmail label on a thread. The label is created automatically if it does not exist.",
    "usage": "gmail-label-message --thread-id <thread-id> --label-name <label-name> --action <action:add|remove> [--raw <json>]",
    "flags": "--thread-id <thread-id> --label-name <label-name> --action <action:add|remove> [--raw <json>]"
  },
  {
    "name": "calendar-list-events",
    "description": "List upcoming Google Calendar events within a time range.",
    "usage": "calendar-list-events [--calendar-id <calendar-id>] [--time-min <time-min:iso-8601>] [--time-max <time-max:iso-8601>] [--max-results <max-results:number>] [--raw <json>]",
    "flags": "[--calendar-id <calendar-id>] [--time-min <time-min:iso-8601>] [--time-max <time-max:iso-8601>] [--max-results <max-results:number>] [--raw <json>]"
  },
  {
    "name": "calendar-create-event",
    "description": "Create a new Google Calendar event with optional attendees and send invites.",
    "usage": "calendar-create-event --title <title> --start <start:iso-8601> --end <end:iso-8601> [--calendar-id <calendar-id>] [--description <description>] [--raw <json>]",
    "flags": "--title <title> --start <start:iso-8601> --end <end:iso-8601> [--calendar-id <calendar-id>] [--description <description>] [--raw <json>]"
  },
  {
    "name": "calendar-smart-search",
    "description": "Retrieve events in a date range and return a clean, noise-free summary. Ideal for understanding current commitments before scheduling.",
    "usage": "calendar-smart-search --start-date <start-date:iso-8601> --end-date <end-date:iso-8601> [--raw <json>]",
    "flags": "--start-date <start-date:iso-8601> --end-date <end-date:iso-8601> [--raw <json>]"
  },
  {
    "name": "calendar-check-conflicts",
    "description": "Check whether a proposed time window overlaps with any existing events. Returns isFree: true if the slot is open.",
    "usage": "calendar-check-conflicts --proposed-start <proposed-start:iso-8601> --proposed-end <proposed-end:iso-8601> [--raw <json>]",
    "flags": "--proposed-start <proposed-start:iso-8601> --proposed-end <proposed-end:iso-8601> [--raw <json>]"
  },
  {
    "name": "calendar-quick-add",
    "description": "Create a calendar event from a natural-language description using Google's own parser.",
    "usage": "calendar-quick-add --text <text> [--calendar-id <calendar-id>] [--raw <json>]",
    "flags": "--text <text> [--calendar-id <calendar-id>] [--raw <json>]"
  },
  {
    "name": "calendar-daily-briefing",
    "description": "Get a clean, time-ordered briefing of all events for a given day across every owned calendar.",
    "usage": "calendar-daily-briefing [--date <date:iso-8601>] [--raw <json>]",
    "flags": "[--date <date:iso-8601>] [--raw <json>]"
  },
  {
    "name": "calendar-block-focus-time",
    "description": "Find the first available free slot and insert a 🛡️ Focus Time event. Checks all owned calendars for conflicts.",
    "usage": "calendar-block-focus-time --duration-minutes <duration-minutes:number> [--within-next-n-days <within-next-n-days:number>] [--calendar-id <calendar-id>] [--raw <json>]",
    "flags": "--duration-minutes <duration-minutes:number> [--within-next-n-days <within-next-n-days:number>] [--calendar-id <calendar-id>] [--raw <json>]"
  },
  {
    "name": "drive-search",
    "description": "Search for files and folders in Google Drive using Drive query syntax.",
    "usage": "drive-search --query <query> [--max-results <max-results:number>] [--raw <json>]",
    "flags": "--query <query> [--max-results <max-results:number>] [--raw <json>]"
  },
  {
    "name": "drive-get-file",
    "description": "Get metadata for a specific Google Drive file by its ID.",
    "usage": "drive-get-file --file-id <file-id> [--raw <json>]",
    "flags": "--file-id <file-id> [--raw <json>]"
  },
  {
    "name": "drive-export-file",
    "description": "Export or download the content of a Google Drive file. Google Workspace files are exported; binary files are returned as base64.",
    "usage": "drive-export-file --file-id <file-id> [--mime-type <mime-type>] [--raw <json>]",
    "flags": "--file-id <file-id> [--mime-type <mime-type>] [--raw <json>]"
  },
  {
    "name": "drive-list-folder",
    "description": "List the contents of a Google Drive folder (subfolders first, then files).",
    "usage": "drive-list-folder --folder-id <folder-id> [--max-results <max-results:number>] [--raw <json>]",
    "flags": "--folder-id <folder-id> [--max-results <max-results:number>] [--raw <json>]"
  },
  {
    "name": "drive-read-doc-markdown",
    "description": "Convert a Google Doc to Markdown, preserving headings, bold/italic, lists, and tables.",
    "usage": "drive-read-doc-markdown --file-id <file-id> [--raw <json>]",
    "flags": "--file-id <file-id> [--raw <json>]"
  },
  {
    "name": "drive-read-sheet-csv",
    "description": "Export a Google Sheet tab as CSV text.",
    "usage": "drive-read-sheet-csv --file-id <file-id> [--sheet-name <sheet-name>] [--range <range>] [--raw <json>]",
    "flags": "--file-id <file-id> [--sheet-name <sheet-name>] [--range <range>] [--raw <json>]"
  },
  {
    "name": "drive-slides-as-text",
    "description": "Extract text from every shape in a Google Slides presentation, returned slide-by-slide.",
    "usage": "drive-slides-as-text --file-id <file-id> [--raw <json>]",
    "flags": "--file-id <file-id> [--raw <json>]"
  },
  {
    "name": "drive-organize-files",
    "description": "Move one or more Drive files into a target folder.",
    "usage": "drive-organize-files --file-ids <file-ids:value1,value2> --target-folder-id <target-folder-id> [--raw <json>]",
    "flags": "--file-ids <file-ids:value1,value2> --target-folder-id <target-folder-id> [--raw <json>]"
  },
  {
    "name": "drive-create-shortcut",
    "description": "Create a Drive shortcut to a file inside a specified folder.",
    "usage": "drive-create-shortcut --file-id <file-id> --folder-id <folder-id> [--raw <json>]",
    "flags": "--file-id <file-id> --folder-id <folder-id> [--raw <json>]"
  },
  {
    "name": "drive-manage-permissions",
    "description": "Grant or revoke a specific user's access to a Drive file. Supports viewer, commenter, and editor roles.",
    "usage": "drive-manage-permissions --file-id <file-id> --email <email:email> [--role <role:viewer|commenter|editor>] --action <action:add|remove> [--raw <json>]",
    "flags": "--file-id <file-id> --email <email:email> [--role <role:viewer|commenter|editor>] --action <action:add|remove> [--raw <json>]"
  },
  {
    "name": "drive-summarize-folder",
    "description": "Get a briefing of a folder — returns names, descriptions, and types of files without reading full content.",
    "usage": "drive-summarize-folder --folder-id <folder-id> [--max-files <max-files:number>] [--raw <json>]",
    "flags": "--folder-id <folder-id> [--max-files <max-files:number>] [--raw <json>]"
  },
  {
    "name": "drive-find-and-replace",
    "description": "Find and replace text (or regex) across an array of Google Docs in a single call.",
    "usage": "drive-find-and-replace --file-ids <file-ids:value1,value2> --find <find> --replace <replace> [--raw <json>]",
    "flags": "--file-ids <file-ids:value1,value2> --find <find> --replace <replace> [--raw <json>]"
  },
  {
    "name": "docs-create",
    "description": "Create a new Google Doc with an optional initial body.",
    "usage": "docs-create --title <title> [--content <content>] [--raw <json>]",
    "flags": "--title <title> [--content <content>] [--raw <json>]"
  },
  {
    "name": "docs-get",
    "description": "Read the full content of a Google Doc, returning body text and structured paragraphs with heading styles.",
    "usage": "docs-get --doc-id <doc-id> [--raw <json>]",
    "flags": "--doc-id <doc-id> [--raw <json>]"
  },
  {
    "name": "docs-append",
    "description": "Append a paragraph of text to the end of an existing Google Doc.",
    "usage": "docs-append --doc-id <doc-id> --content <content> [--add-newline <add-newline:true|false>] [--raw <json>]",
    "flags": "--doc-id <doc-id> --content <content> [--add-newline <add-newline:true|false>] [--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "schemaVersion": 1,
  "generatedAt": "2026-02-23T05:35:00.051Z",
  "generator": {
    "name": "mcp-google-workspace",
    "version": "1.0.0"
  },
  "server": {
    "name": "index",
    "source": {
      "kind": "local",
      "path": "<adhoc>"
    },
    "definition": {
      "name": "index",
      "description": "mcp-google-workspace",
      "command": {
        "kind": "stdio",
        "command": "node",
        "args": [
          "/home/tyler/mcp-google-workspace/mcp/dist/index.js"
        ]
      }
    }
  },
  "artifact": {
    "path": "",
    "kind": "template"
  },
  "invocation": {
    "serverRef": "{\"name\":\"index\",\"command\":{\"kind\":\"stdio\",\"command\":\"node\",\"args\":[\"/home/tyler/mcp-google-workspace/mcp/dist/index.js\"]},\"source\":{\"kind\":\"local\",\"path\":\"<adhoc>\"}}",
    "configPath": "<adhoc>",
    "runtime": "node",
    "bundler": "rolldown",
    "timeoutMs": 30000,
    "minify": false
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 30000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "gmail-search": "function gmail_search(query: string, maxResults?: number);",
  "gmail-get-message": "function gmail_get_message(messageId: string);",
  "gmail-send-draft": "function gmail_send_draft(to: string, subject: string, body: string, cc?: string, bcc?: string);",
  "gmail-get-messages": "function gmail_get_messages(query: string, maxResults?: number);",
  "gmail-modify-message": "function gmail_modify_message(messageId: string, markRead?: boolean, star?: boolean, trash?: boolean, archive?: boolean);",
  "gmail-label-message": "function gmail_label_message(threadId: string, labelName: string, action: \"add\" | \"remove\");",
  "calendar-list-events": "function calendar_list_events(calendarId?: string, timeMin?: string, timeMax?: string, maxResults?: number);",
  "calendar-create-event": "function calendar_create_event(title: string, start: string, end: string, calendarId?: string, description?: string);",
  "calendar-smart-search": "function calendar_smart_search(startDate: string, endDate: string);",
  "calendar-check-conflicts": "function calendar_check_conflicts(proposedStart: string, proposedEnd: string);",
  "calendar-quick-add": "function calendar_quick_add(text: string, calendarId?: string);",
  "calendar-daily-briefing": "function calendar_daily_briefing(date?: string);",
  "calendar-block-focus-time": "function calendar_block_focus_time(durationMinutes: number, withinNextNDays?: number, calendarId?: string);",
  "drive-search": "function drive_search(query: string, maxResults?: number);",
  "drive-get-file": "function drive_get_file(fileId: string);",
  "drive-export-file": "function drive_export_file(fileId: string, mimeType?: string);",
  "drive-list-folder": "function drive_list_folder(folderId: string, maxResults?: number);",
  "drive-read-doc-markdown": "function drive_read_doc_markdown(fileId: string);",
  "drive-read-sheet-csv": "function drive_read_sheet_csv(fileId: string, sheetName?: string, range?: string);",
  "drive-slides-as-text": "function drive_slides_as_text(fileId: string);",
  "drive-organize-files": "function drive_organize_files(fileIds: string[], targetFolderId: string);",
  "drive-create-shortcut": "function drive_create_shortcut(fileId: string, folderId: string);",
  "drive-manage-permissions": "function drive_manage_permissions(fileId: string, email: string, role?: \"viewer\" | \"commenter\" | \"editor\", action: \"add\" | \"remove\");",
  "drive-summarize-folder": "function drive_summarize_folder(folderId: string, maxFiles?: number);",
  "drive-find-and-replace": "function drive_find_and_replace(fileIds: string[], find: string, replace: string);",
  "docs-create": "function docs_create(title: string, content?: string);",
  "docs-get": "function docs_get(docId: string);",
  "docs-append": "function docs_append(docId: string, content: string, addNewline?: boolean);"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("gmail-search")
	.summary("gmail-search --query <query> [--max-results <max-results:number>] [--raw <json>]")
	.description("Search Gmail threads using the same query syntax as the Gmail search bar. Returns thread metadata including subject, sender, date, and read status.")
	.usage("--query <query> [--max-results <max-results:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--query <query>", "Gmail search query (same syntax as the Gmail search bar)")
	.option("--max-results <max-results:number>", "Maximum number of threads to return (1-50, default 10) (default: 10; example: 10)", (value) => parseFloat(value))
	
	.alias("gmail_search")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.query !== undefined) args.query = cmdOpts.query;
		if (cmdOpts.maxResults !== undefined) args.maxResults = cmdOpts.maxResults;
			const call = (proxy.gmailSearch as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.gmail_search(query: \"value\", maxResults: 10)");

program
	.command("gmail-get-message")
	.summary("gmail-get-message --message-id <message-id> [--raw <json>]")
	.description("Retrieve the full content of a single Gmail message by its ID, including headers, plain-text body, and attachment metadata.")
	.usage("--message-id <message-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--message-id <message-id>", "The Gmail message ID to retrieve (example: example-id)")
	
	.alias("gmail_get_message")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.messageId !== undefined) args.messageId = cmdOpts.messageId;
			const call = (proxy.gmailGetMessage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.gmail_get_message(messageId: \"example-id\")");

program
	.command("gmail-send-draft")
	.summary("gmail-send-draft --to <to> --subject <subject> --body <body> [--cc <cc>] [--bcc <bcc>] [--raw <json>]")
	.description("Create a Gmail draft and immediately send it.")
	.usage("--to <to> --subject <subject> --body <body> [--cc <cc>] [--bcc <bcc>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--to <to>", "Recipient email address")
	.requiredOption("--subject <subject>", "Email subject")
	.requiredOption("--body <body>", "Plain text email body")
	.option("--cc <cc>", "CC recipients (comma-separated)")
	.option("--bcc <bcc>", "BCC recipients (comma-separated)")
	
	.alias("gmail_send_draft")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.to !== undefined) args.to = cmdOpts.to;
		if (cmdOpts.subject !== undefined) args.subject = cmdOpts.subject;
		if (cmdOpts.body !== undefined) args.body = cmdOpts.body;
		if (cmdOpts.cc !== undefined) args.cc = cmdOpts.cc;
		if (cmdOpts.bcc !== undefined) args.bcc = cmdOpts.bcc;
			const call = (proxy.gmailSendDraft as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.gmail_send_draft(to: \"value\", subject: \"value\", body:, ...)");

program
	.command("gmail-get-messages")
	.summary("gmail-get-messages --query <query> [--max-results <max-results:number>] [--raw <json>]")
	.description("Bulk-fetch full message content (subject, headers, body, attachments) for all emails matching a Gmail search query. Ideal for \"get all unread emails\" type requests.")
	.usage("--query <query> [--max-results <max-results:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--query <query>", "Gmail search query (e.g. \"is:unread\", \"from:boss@company.com\")")
	.option("--max-results <max-results:number>", "Max threads to expand, each with all messages (1-20, default 5) (default: 5; example: 5)", (value) => parseFloat(value))
	
	.alias("gmail_get_messages")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.query !== undefined) args.query = cmdOpts.query;
		if (cmdOpts.maxResults !== undefined) args.maxResults = cmdOpts.maxResults;
			const call = (proxy.gmailGetMessages as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.gmail_get_messages(query: \"value\", maxResults: 5)");

program
	.command("gmail-modify-message")
	.summary("gmail-modify-message --message-id <message-id> [--mark-read <mark-read:true|false>] [--star <star:true|false>] [--trash <trash:true|false>] [--archive <archive:true|false>] [--raw <json>]")
	.description("Modify the state of a Gmail message: mark it read/unread, star/unstar it, move it to trash, or archive its thread.")
	.usage("--message-id <message-id> [--mark-read <mark-read:true|false>] [--star <star:true|false>] [--trash <trash:true|false>] [--archive <archive:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--message-id <message-id>", "The Gmail message ID to modify (example: example-id)")
	.option("--mark-read <mark-read:true|false>", "true = mark as read, false = mark as unread (example: true)", (value) => value !== 'false')
	.option("--star <star:true|false>", "true = star the message, false = unstar (example: true)", (value) => value !== 'false')
	.option("--trash <trash:true|false>", "true = move the message to Trash (example: true)", (value) => value !== 'false')
	.option("--archive <archive:true|false>", "true = archive the thread (remove from Inbox) (example: true)", (value) => value !== 'false')
	
	.alias("gmail_modify_message")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.messageId !== undefined) args.messageId = cmdOpts.messageId;
		if (cmdOpts.markRead !== undefined) args.markRead = cmdOpts.markRead;
		if (cmdOpts.star !== undefined) args.star = cmdOpts.star;
		if (cmdOpts.trash !== undefined) args.trash = cmdOpts.trash;
		if (cmdOpts.archive !== undefined) args.archive = cmdOpts.archive;
			const call = (proxy.gmailModifyMessage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.gmail_modify_message(messageId: \"example-id\", markRead, ...)");

program
	.command("gmail-label-message")
	.summary("gmail-label-message --thread-id <thread-id> --label-name <label-name> --action <action:add|remove> [--raw <json>]")
	.description("Apply or remove a named Gmail label on a thread. The label is created automatically if it does not exist.")
	.usage("--thread-id <thread-id> --label-name <label-name> --action <action:add|remove> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--thread-id <thread-id>", "The Gmail thread ID to label (example: example-id)")
	.requiredOption("--label-name <label-name>", "Label name to apply or remove. Created automatically on \"add\" if it does not exist.")
	.requiredOption("--action <action:add|remove>", "\"add\" to apply the label, \"remove\" to remove it (choices: add, remove; example: add)")
	
	.alias("gmail_label_message")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.threadId !== undefined) args.threadId = cmdOpts.threadId;
		if (cmdOpts.labelName !== undefined) args.labelName = cmdOpts.labelName;
		if (cmdOpts.action !== undefined) args.action = cmdOpts.action;
			const call = (proxy.gmailLabelMessage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.gmail_label_message(threadId: \"example-id\", labelName:, ...)");

program
	.command("calendar-list-events")
	.summary("calendar-list-events [--calendar-id <calendar-id>] [--time-min <time-min:iso-8601>] [--time-max <time-max:iso-8601>] [--max-results <max-results:number>] [--raw <json>]")
	.description("List upcoming Google Calendar events within a time range.")
	.usage("[--calendar-id <calendar-id>] [--time-min <time-min:iso-8601>] [--time-max <time-max:iso-8601>] [--max-results <max-results:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--calendar-id <calendar-id>", "Calendar ID (default: \"primary\") (default: primary; example: primary)")
	.option("--time-min <time-min:iso-8601>", "Start of time range in ISO 8601 format (defaults to now)")
	.option("--time-max <time-max:iso-8601>", "End of time range in ISO 8601 format")
	.option("--max-results <max-results:number>", "Max events to return (1-50, default 10) (default: 10; example: 10)", (value) => parseFloat(value))
	
	.alias("calendar_list_events")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.calendarId !== undefined) args.calendarId = cmdOpts.calendarId;
		if (cmdOpts.timeMin !== undefined) args.timeMin = cmdOpts.timeMin;
		if (cmdOpts.timeMax !== undefined) args.timeMax = cmdOpts.timeMax;
		if (cmdOpts.maxResults !== undefined) args.maxResults = cmdOpts.maxResults;
			const call = (proxy.calendarListEvents as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.calendar_list_events(calendarId: \"primary\", maxResults: 10)");

program
	.command("calendar-create-event")
	.summary("calendar-create-event --title <title> --start <start:iso-8601> --end <end:iso-8601> [--calendar-id <calendar-id>] [--description <description>] [--raw <json>]")
	.description("Create a new Google Calendar event with optional attendees and send invites.")
	.usage("--title <title> --start <start:iso-8601> --end <end:iso-8601> [--calendar-id <calendar-id>] [--description <description>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--title <title>", "Event title / summary")
	.requiredOption("--start <start:iso-8601>", "Event start time in ISO 8601 format")
	.requiredOption("--end <end:iso-8601>", "Event end time in ISO 8601 format")
	.option("--calendar-id <calendar-id>", "Calendar ID (default: \"primary\") (default: primary; example: primary)")
	.option("--description <description>", "Event description")
	.option("--location <location>", "Event location")
	.option("--attendees <attendees:value1,value2>", "List of attendee email addresses (example: value1,value2)", (value) => value.split(',').map((v) => v.trim()))
	.option("--send-invites <send-invites:true|false>", "Whether to send invite emails (default: true) (default: true; example: true)", (value) => value !== 'false')
	
	.alias("calendar_create_event")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.title !== undefined) args.title = cmdOpts.title;
		if (cmdOpts.start !== undefined) args.start = cmdOpts.start;
		if (cmdOpts.end !== undefined) args.end = cmdOpts.end;
		if (cmdOpts.calendarId !== undefined) args.calendarId = cmdOpts.calendarId;
		if (cmdOpts.description !== undefined) args.description = cmdOpts.description;
		if (cmdOpts.location !== undefined) args.location = cmdOpts.location;
		if (cmdOpts.attendees !== undefined) args.attendees = cmdOpts.attendees;
		if (cmdOpts.sendInvites !== undefined) args.sendInvites = cmdOpts.sendInvites;
			const call = (proxy.calendarCreateEvent as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.calendar_create_event(title: \"value\", start: \"value\", ...)")
	.addHelpText('afterAll', () => '\n' + "// optional (3): location, attendees, sendInvites" + '\n');

program
	.command("calendar-smart-search")
	.summary("calendar-smart-search --start-date <start-date:iso-8601> --end-date <end-date:iso-8601> [--raw <json>]")
	.description("Retrieve events in a date range and return a clean, noise-free summary. Ideal for understanding current commitments before scheduling.")
	.usage("--start-date <start-date:iso-8601> --end-date <end-date:iso-8601> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--start-date <start-date:iso-8601>", "Start of the date range in ISO 8601 format (e.g. \"2026-02-20\")")
	.requiredOption("--end-date <end-date:iso-8601>", "End of the date range in ISO 8601 format (e.g. \"2026-02-27\")")
	
	.alias("calendar_smart_search")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.startDate !== undefined) args.startDate = cmdOpts.startDate;
		if (cmdOpts.endDate !== undefined) args.endDate = cmdOpts.endDate;
			const call = (proxy.calendarSmartSearch as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.calendar_smart_search(startDate: \"value\", endDate: \"value\")");

program
	.command("calendar-check-conflicts")
	.summary("calendar-check-conflicts --proposed-start <proposed-start:iso-8601> --proposed-end <proposed-end:iso-8601> [--raw <json>]")
	.description("Check whether a proposed time window overlaps with any existing events. Returns isFree: true if the slot is open.")
	.usage("--proposed-start <proposed-start:iso-8601> --proposed-end <proposed-end:iso-8601> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--proposed-start <proposed-start:iso-8601>", "Proposed event start time in ISO 8601 format")
	.requiredOption("--proposed-end <proposed-end:iso-8601>", "Proposed event end time in ISO 8601 format")
	
	.alias("calendar_check_conflicts")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.proposedStart !== undefined) args.proposedStart = cmdOpts.proposedStart;
		if (cmdOpts.proposedEnd !== undefined) args.proposedEnd = cmdOpts.proposedEnd;
			const call = (proxy.calendarCheckConflicts as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.calendar_check_conflicts(proposedStart: \"value\", propo, ...)");

program
	.command("calendar-quick-add")
	.summary("calendar-quick-add --text <text> [--calendar-id <calendar-id>] [--raw <json>]")
	.description("Create a calendar event from a natural-language description using Google's own parser.")
	.usage("--text <text> [--calendar-id <calendar-id>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--text <text>", "Natural-language event description (e.g. \"Lunch with Sarah next Tuesday at 1pm\")")
	.option("--calendar-id <calendar-id>", "Calendar ID (default: \"primary\") (default: primary; example: primary)")
	
	.alias("calendar_quick_add")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.text !== undefined) args.text = cmdOpts.text;
		if (cmdOpts.calendarId !== undefined) args.calendarId = cmdOpts.calendarId;
			const call = (proxy.calendarQuickAdd as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.calendar_quick_add(text: \"value\", calendarId: \"primary\")");

program
	.command("calendar-daily-briefing")
	.summary("calendar-daily-briefing [--date <date:iso-8601>] [--raw <json>]")
	.description("Get a clean, time-ordered briefing of all events for a given day across every owned calendar.")
	.usage("[--date <date:iso-8601>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--date <date:iso-8601>", "Date in ISO 8601 format (e.g. \"2026-02-20\"). Defaults to today.")
	
	.alias("calendar_daily_briefing")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.date !== undefined) args.date = cmdOpts.date;
			const call = (proxy.calendarDailyBriefing as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.calendar_daily_briefing()");

program
	.command("calendar-block-focus-time")
	.summary("calendar-block-focus-time --duration-minutes <duration-minutes:number> [--within-next-n-days <within-next-n-days:number>] [--calendar-id <calendar-id>] [--raw <json>]")
	.description("Find the first available free slot and insert a 🛡️ Focus Time event. Checks all owned calendars for conflicts.")
	.usage("--duration-minutes <duration-minutes:number> [--within-next-n-days <within-next-n-days:number>] [--calendar-id <calendar-id>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--duration-minutes <duration-minutes:number>", "Focus block length in minutes (e.g. 90 for 1.5 hours) (example: 1)", (value) => parseFloat(value))
	.option("--within-next-n-days <within-next-n-days:number>", "Days ahead to scan for a free slot (default: 7, max: 30). Weekdays 9 AM–6 PM only. (default: 7; example: 7)", (value) => parseFloat(value))
	.option("--calendar-id <calendar-id>", "Calendar to book the focus block on (default: \"primary\") (default: primary; example: primary)")
	
	.alias("calendar_block_focus_time")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.durationMinutes !== undefined) args.durationMinutes = cmdOpts.durationMinutes;
		if (cmdOpts.withinNextNDays !== undefined) args.withinNextNDays = cmdOpts.withinNextNDays;
		if (cmdOpts.calendarId !== undefined) args.calendarId = cmdOpts.calendarId;
			const call = (proxy.calendarBlockFocusTime as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.calendar_block_focus_time(durationMinutes: 1, withinNe, ...)");

program
	.command("drive-search")
	.summary("drive-search --query <query> [--max-results <max-results:number>] [--raw <json>]")
	.description("Search for files and folders in Google Drive using Drive query syntax.")
	.usage("--query <query> [--max-results <max-results:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--query <query>", "Drive search query (e.g. \"name contains 'report'\" or \"mimeType='application/vnd.google-apps.document'\")")
	.option("--max-results <max-results:number>", "Max files to return (1-50, default 10) (default: 10; example: 10)", (value) => parseFloat(value))
	
	.alias("drive_search")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.query !== undefined) args.query = cmdOpts.query;
		if (cmdOpts.maxResults !== undefined) args.maxResults = cmdOpts.maxResults;
			const call = (proxy.driveSearch as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_search(query: \"value\", maxResults: 10)");

program
	.command("drive-get-file")
	.summary("drive-get-file --file-id <file-id> [--raw <json>]")
	.description("Get metadata for a specific Google Drive file by its ID.")
	.usage("--file-id <file-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--file-id <file-id>", "The Drive file ID (example: example-id)")
	
	.alias("drive_get_file")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fileId !== undefined) args.fileId = cmdOpts.fileId;
			const call = (proxy.driveGetFile as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_get_file(fileId: \"example-id\")");

program
	.command("drive-export-file")
	.summary("drive-export-file --file-id <file-id> [--mime-type <mime-type>] [--raw <json>]")
	.description("Export or download the content of a Google Drive file. Google Workspace files are exported; binary files are returned as base64.")
	.usage("--file-id <file-id> [--mime-type <mime-type>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--file-id <file-id>", "The Drive file ID to export (example: example-id)")
	.option("--mime-type <mime-type>", "Target MIME type (default: \"text/plain\"). Use \"application/pdf\" for PDFs. Binary files are returned as base64. (default: text/plain; example: text/plain)")
	
	.alias("drive_export_file")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fileId !== undefined) args.fileId = cmdOpts.fileId;
		if (cmdOpts.mimeType !== undefined) args.mimeType = cmdOpts.mimeType;
			const call = (proxy.driveExportFile as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_export_file(fileId: \"example-id\", mimeType: \"tex, ...)");

program
	.command("drive-list-folder")
	.summary("drive-list-folder --folder-id <folder-id> [--max-results <max-results:number>] [--raw <json>]")
	.description("List the contents of a Google Drive folder (subfolders first, then files).")
	.usage("--folder-id <folder-id> [--max-results <max-results:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--folder-id <folder-id>", "The Drive folder ID to list. Use \"root\" for My Drive root. (example: example-id)")
	.option("--max-results <max-results:number>", "Max items to return (default: 50) (default: 50; example: 50)", (value) => parseFloat(value))
	
	.alias("drive_list_folder")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.folderId !== undefined) args.folderId = cmdOpts.folderId;
		if (cmdOpts.maxResults !== undefined) args.maxResults = cmdOpts.maxResults;
			const call = (proxy.driveListFolder as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_list_folder(folderId: \"example-id\", maxResults: 50)");

program
	.command("drive-read-doc-markdown")
	.summary("drive-read-doc-markdown --file-id <file-id> [--raw <json>]")
	.description("Convert a Google Doc to Markdown, preserving headings, bold/italic, lists, and tables.")
	.usage("--file-id <file-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--file-id <file-id>", "The Google Doc file ID to convert to Markdown (example: example-id)")
	
	.alias("drive_read_doc_markdown")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fileId !== undefined) args.fileId = cmdOpts.fileId;
			const call = (proxy.driveReadDocMarkdown as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_read_doc_markdown(fileId: \"example-id\")");

program
	.command("drive-read-sheet-csv")
	.summary("drive-read-sheet-csv --file-id <file-id> [--sheet-name <sheet-name>] [--range <range>] [--raw <json>]")
	.description("Export a Google Sheet tab as CSV text.")
	.usage("--file-id <file-id> [--sheet-name <sheet-name>] [--range <range>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--file-id <file-id>", "The Google Sheets file ID to export as CSV (example: example-id)")
	.option("--sheet-name <sheet-name>", "Sheet/tab name (defaults to the active sheet)")
	.option("--range <range>", "A1 notation range (e.g. \"A1:E20\"). Defaults to all data.")
	
	.alias("drive_read_sheet_csv")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fileId !== undefined) args.fileId = cmdOpts.fileId;
		if (cmdOpts.sheetName !== undefined) args.sheetName = cmdOpts.sheetName;
		if (cmdOpts.range !== undefined) args.range = cmdOpts.range;
			const call = (proxy.driveReadSheetCsv as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_read_sheet_csv(fileId: \"example-id\")");

program
	.command("drive-slides-as-text")
	.summary("drive-slides-as-text --file-id <file-id> [--raw <json>]")
	.description("Extract text from every shape in a Google Slides presentation, returned slide-by-slide.")
	.usage("--file-id <file-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--file-id <file-id>", "The Google Slides file ID to extract text from (example: example-id)")
	
	.alias("drive_slides_as_text")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fileId !== undefined) args.fileId = cmdOpts.fileId;
			const call = (proxy.driveSlidesAsText as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_slides_as_text(fileId: \"example-id\")");

program
	.command("drive-organize-files")
	.summary("drive-organize-files --file-ids <file-ids:value1,value2> --target-folder-id <target-folder-id> [--raw <json>]")
	.description("Move one or more Drive files into a target folder.")
	.usage("--file-ids <file-ids:value1,value2> --target-folder-id <target-folder-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--file-ids <file-ids:value1,value2>", "Array of Drive file IDs to move (example: value1,value2)", (value) => value.split(',').map((v) => v.trim()))
	.requiredOption("--target-folder-id <target-folder-id>", "The destination folder ID (example: example-id)")
	
	.alias("drive_organize_files")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fileIds !== undefined) args.fileIds = cmdOpts.fileIds;
		if (cmdOpts.targetFolderId !== undefined) args.targetFolderId = cmdOpts.targetFolderId;
			const call = (proxy.driveOrganizeFiles as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_organize_files(fileIds: [\"value1\", \"value2\"], ta, ...)");

program
	.command("drive-create-shortcut")
	.summary("drive-create-shortcut --file-id <file-id> --folder-id <folder-id> [--raw <json>]")
	.description("Create a Drive shortcut to a file inside a specified folder.")
	.usage("--file-id <file-id> --folder-id <folder-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--file-id <file-id>", "The Drive file ID to create a shortcut for (example: example-id)")
	.requiredOption("--folder-id <folder-id>", "Folder ID where the shortcut is placed. Use \"root\" for My Drive root. (example: example-id)")
	
	.alias("drive_create_shortcut")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fileId !== undefined) args.fileId = cmdOpts.fileId;
		if (cmdOpts.folderId !== undefined) args.folderId = cmdOpts.folderId;
			const call = (proxy.driveCreateShortcut as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_create_shortcut(fileId: \"example-id\", folderId:, ...)");

program
	.command("drive-manage-permissions")
	.summary("drive-manage-permissions --file-id <file-id> --email <email:email> [--role <role:viewer|commenter|editor>] --action <action:add|remove> [--raw <json>]")
	.description("Grant or revoke a specific user's access to a Drive file. Supports viewer, commenter, and editor roles.")
	.usage("--file-id <file-id> --email <email:email> [--role <role:viewer|commenter|editor>] --action <action:add|remove> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--file-id <file-id>", "The Drive file ID to manage permissions for (example: example-id)")
	.requiredOption("--email <email:email>", "Email address of the user to grant or revoke access")
	.option("--role <role:viewer|commenter|editor>", "Access level (default: \"viewer\"). Only used when action is \"add\". (choices: viewer, commenter, editor; default: viewer; example: viewer)")
	.requiredOption("--action <action:add|remove>", "\"add\" to grant access, \"remove\" to revoke it (choices: add, remove; example: add)")
	
	.alias("drive_manage_permissions")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fileId !== undefined) args.fileId = cmdOpts.fileId;
		if (cmdOpts.email !== undefined) args.email = cmdOpts.email;
		if (cmdOpts.role !== undefined) args.role = cmdOpts.role;
		if (cmdOpts.action !== undefined) args.action = cmdOpts.action;
			const call = (proxy.driveManagePermissions as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_manage_permissions(fileId: \"example-id\", email:, ...)");

program
	.command("drive-summarize-folder")
	.summary("drive-summarize-folder --folder-id <folder-id> [--max-files <max-files:number>] [--raw <json>]")
	.description("Get a briefing of a folder — returns names, descriptions, and types of files without reading full content.")
	.usage("--folder-id <folder-id> [--max-files <max-files:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--folder-id <folder-id>", "The Drive folder ID to summarize. Use \"root\" for My Drive root. (example: example-id)")
	.option("--max-files <max-files:number>", "Max files to include (default: 10, max: 20) (default: 10; example: 10)", (value) => parseFloat(value))
	
	.alias("drive_summarize_folder")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.folderId !== undefined) args.folderId = cmdOpts.folderId;
		if (cmdOpts.maxFiles !== undefined) args.maxFiles = cmdOpts.maxFiles;
			const call = (proxy.driveSummarizeFolder as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_summarize_folder(folderId: \"example-id\", maxFiles: 10)");

program
	.command("drive-find-and-replace")
	.summary("drive-find-and-replace --file-ids <file-ids:value1,value2> --find <find> --replace <replace> [--raw <json>]")
	.description("Find and replace text (or regex) across an array of Google Docs in a single call.")
	.usage("--file-ids <file-ids:value1,value2> --find <find> --replace <replace> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--file-ids <file-ids:value1,value2>", "Array of Google Doc file IDs to run find-and-replace on (example: value1,value2)", (value) => value.split(',').map((v) => v.trim()))
	.requiredOption("--find <find>", "Text (or regex) to search for")
	.requiredOption("--replace <replace>", "Replacement text")
	
	.alias("drive_find_and_replace")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fileIds !== undefined) args.fileIds = cmdOpts.fileIds;
		if (cmdOpts.find !== undefined) args.find = cmdOpts.find;
		if (cmdOpts.replace !== undefined) args.replace = cmdOpts.replace;
			const call = (proxy.driveFindAndReplace as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.drive_find_and_replace(fileIds: [\"value1\", \"value2\"], ...)");

program
	.command("docs-create")
	.summary("docs-create --title <title> [--content <content>] [--raw <json>]")
	.description("Create a new Google Doc with an optional initial body.")
	.usage("--title <title> [--content <content>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--title <title>", "Title for the new Google Doc")
	.option("--content <content>", "Initial body text for the document")
	
	.alias("docs_create")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.title !== undefined) args.title = cmdOpts.title;
		if (cmdOpts.content !== undefined) args.content = cmdOpts.content;
			const call = (proxy.docsCreate as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.docs_create(title: \"value\")");

program
	.command("docs-get")
	.summary("docs-get --doc-id <doc-id> [--raw <json>]")
	.description("Read the full content of a Google Doc, returning body text and structured paragraphs with heading styles.")
	.usage("--doc-id <doc-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--doc-id <doc-id>", "The Google Doc ID (example: example-id)")
	
	.alias("docs_get")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.docId !== undefined) args.docId = cmdOpts.docId;
			const call = (proxy.docsGet as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.docs_get(docId: \"example-id\")");

program
	.command("docs-append")
	.summary("docs-append --doc-id <doc-id> --content <content> [--add-newline <add-newline:true|false>] [--raw <json>]")
	.description("Append a paragraph of text to the end of an existing Google Doc.")
	.usage("--doc-id <doc-id> --content <content> [--add-newline <add-newline:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--doc-id <doc-id>", "The Google Doc ID to append to (example: example-id)")
	.requiredOption("--content <content>", "The text content to append")
	.option("--add-newline <add-newline:true|false>", "Add a blank line before the appended content (default: true) (default: true; example: true)", (value) => value !== 'false')
	
	.alias("docs_append")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.docId !== undefined) args.docId = cmdOpts.docId;
		if (cmdOpts.content !== undefined) args.content = cmdOpts.content;
		if (cmdOpts.addNewline !== undefined) args.addNewline = cmdOpts.addNewline;
			const call = (proxy.docsAppend as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call index.docs_append(docId: \"example-id\", content: \"value\", add, ...)");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n');
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}

function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			break;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(wrapped.raw, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(wrapped.raw, null, 2));
	}
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				args: [ ...((server.command as any).args ?? []) ],
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime(): Promise<Awaited<ReturnType<typeof createRuntime>>> {
	return await createRuntime({
		servers: [normalizeEmbeddedServer(embeddedServer)],
	});
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
